environment:
  build_version: 5.0.1
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)'
before_build:
 - cmd: dotnet restore src/Grace.WCF
build:
  project: Grace.WCF.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_build:
- cmd: dotnet pack src/Grace.WCF/project.json -o . -c Release --version-suffix Nightly%APPVEYOR_BUILD_NUMBER%
artifacts:
- path: Grace*.nupkg
  name: Grace
