environment:
  build_version: 6.1.1
  Version: $(build_version)-Nightly%APPVEYOR_BUILD_NUMBER%
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)'
before_build:
 - cmd: nuget restore Grace.WCF.sln
build:
  project: Grace.WCF.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_build:
- cmd: msbuild /t:pack src/Grace.WCF/Grace.WCF.csproj /p:Configuration=Release /p:IncludeSymbols=true /p:PackageOutputPath=..\..\
artifacts:
- path: Grace*.nupkg
  name: Grace
os: Visual Studio 2017